apiVersion: batch/v1
kind: Job
metadata:
  name: pattern-mining3
  namespace: matheussenna
spec:
  template:
    spec:
      volumes:
      - name: playlist-recommendation-storage
        persistentVolumeClaim:
          claimName: matheussenna-playlist-recommendation-pvc
      containers:
      - name: pattern-mining-model
        image: docker.io/matheusfarnese/pattern-mining:v2
        envFrom:
        - configMapRef:
            name: playlist-recommendation-configmap
        env:
        - name: DATASET_URL
          value: "https://raw.githubusercontent.com/MatheusFarnese/cloudcomputingTP2/main/dataset/spotify_dataset.csv"
        volumeMounts:
        - mountPath: "/app/data"
          name: playlist-recommendation-storage
      restartPolicy: Never
  backoffLimit: 4
