apiVersion: v1
kind: Service
metadata:
  name: playlist-recommendation-service
  namespace: matheussenna
spec:
  selector:
    app: playlist-recommendation
  ports:
    - protocol: TCP
      port: 52004
      targetPort: 8000
